### ISSUE TITLE
Misprint in instructional comment

### ISSUE THREAD

**Issue by bl17zar** [tommyod/Efficient-Apriori#13]
Hi! You have misprint in rules.py line 54.
Now: ```        >>> r.support  # Probability of ('a', 'c', 'c') in the data``` 
Should be: ```        >>> r.support  # Probability of ('a', 'b, 'c') in the data```

It is a good package, I just want to be helpful)

**Comment by tommyod** [comment]
Thanks @bl17zar . Wanna edit the file and make a PR? If not I'll fix it.

**Comment by bl17zar** [comment]
@tommyod yes, I ll do it ;)
