### ISSUE TITLE
Why not add Rule Power Factor (RPF) as one more property to Rule?

### ISSUE THREAD

**Issue by bl17zar** [tommyod/Efficient-Apriori#16]
According to this https://en.wikipedia.org/wiki/Association_rule_learning#Useful_Concepts it would be very reasonable to add RPF as method to Rule instance. Moreover it is not computationally hard and provides good insights on algorithm results.

I would be glad to contribute with PR.

**Comment by tommyod** [comment]
Seems very reasonable. Please go ahead @bl17zar . Thanks for the help!
