### ISSUE TITLE
Is there any way to export the rules with data to Excel?

### ISSUE THREAD

**Issue by TimHellegers** [tommyod/Efficient-Apriori#23]
I can't figure out how to write the results of the rules to a list or dataset. I'm only able to write the rules to lists without the calculations like lift, conv etc..
How can I capture the results in a list or dataframe so I'm able to export this to Excel/CSV?

Using the following code, I put the rules in a list without results.
`association_results = filter(lambda rule: len(rule.lhs) == 2 and len(rule.rhs) == 1, rules)
rulelist = []
for rule in sorted(association_results, key=lambda rule: rule.lift):
  rulelist.append(rule)`

**Comment by tommyod** [comment]
Do something like this:

```python  
from efficient_apriori import apriori
transactions = [('eggs', 'bacon', 'soup'),
                ('eggs', 'bacon', 'apple'),
                ('soup', 'bacon', 'banana')]
itemsets, rules = apriori(transactions, min_support=0.5,  min_confidence=1)

association_results = filter(lambda rule: len(rule.lhs) == 1 and len(rule.rhs) == 1, rules)
rules_as_lists = [list(rule.lhs) + list(rule.rhs) for rule in association_results]
print(rules_as_lists)


import pandas as pd
df = pd.DataFrame(rules_as_lists)

```

**Comment by TimHellegers** [comment]
@tommyod Yes, this is a good way to put the products in a dataframe. But the problem I'm facing is that I don't have the values (conf., lift, supp.). Is there anyway to append these values in the list/dataframe?
I can't use the values if I can only print them. I will also check if can calculate the values myself and put them in the dataset.

**Comment by tommyod** [comment]
Just write e.g. 
```python
rules_as_lists = [list(rule.lhs) + list(rule.rhs) + [rule.lift] for rule in association_results]
```
to get the lift as the final column.

If you haven't already, I recommend reading the official Python tutorial. Then you'll learn how to use object attributes in general and you can solve similar problems.

**Comment by TimHellegers** [comment]
Thanks for the tip! Code works perfect now.
