### ISSUE TITLE
ModuleNotFoundError: No module named 'dataclasses'

### ISSUE THREAD

**Issue by penghusile** [tommyod/Efficient-Apriori#29]
environment：anaconda 3-5.2.0 
I just ran the sample code and it reported an error.

`ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-7-e8973ea19b4b> in <module>
----> 1 from efficient_apriori import apriori
      2 transactions = [('eggs', 'bacon', 'soup'),
      3                 ('eggs', 'bacon', 'apple'),
      4                 ('soup', 'bacon', 'banana')]
      5 itemsets, rules = apriori(transactions, min_support=0.5, min_confidence=1)

E:\anaconda\lib\site-packages\efficient_apriori\__init__.py in <module>
     10 
     11 import sys
---> 12 from efficient_apriori.apriori import apriori
     13 from efficient_apriori.itemsets import itemsets_from_transactions
     14 from efficient_apriori.rules import Rule, generate_rules_apriori

E:\anaconda\lib\site-packages\efficient_apriori\apriori.py in <module>
      6 
      7 import typing
----> 8 from efficient_apriori.itemsets import itemsets_from_transactions, ItemsetCount
      9 from efficient_apriori.rules import generate_rules_apriori
     10 

E:\anaconda\lib\site-packages\efficient_apriori\itemsets.py in <module>
     13 
     14 from collections import defaultdict
---> 15 from dataclasses import field, dataclass
     16 
     17 

ModuleNotFoundError: No module named 'dataclasses'`

**Comment by tommyod** [comment]
It's likely due to not being on Python 3.6+.

Try this with e.g. Python 3.7. In the terminal:
```bash
conda create --name py37 anaconda python=3.7 --yes
conda activate py37
pip install efficient-apriori
python -c "import efficient_apriori as e; print(e.__version__)"
```

**Comment by penghusile** [comment]
it works，thanks.
