### ISSUE TITLE
A doubt

### ISSUE THREAD

**Issue by Andhu7** [tommyod/Efficient-Apriori#5]
How can i get intersection of 2 rules..for example rules[0] and rule[1] i.e the number of transactions that satisfies rules[0] and rules[1]

**Comment by tommyod** [comment]
This seems to be a mathematical question, which is unrelated to the software.

Some thoughts: If you have two rules, what is your definition of the intersection? Is the intersection of `{a, b} -> {c}` and  `{a} -> {c, d}` equal to  `{a} -> {c}`? What do you mean by number of transactions satisfying a rule? Do you mean every time `{a, c}` appear together in a transaction?

It's not obvious to me what you're asking, nor it is obvious that the apriori algorithm in it's original form solves the problem. If I have completely misunderstood, and this question is related to the software implementation, then feel free to discuss. If not, I am afraid I am of little help.

**Comment by Andhu7** [comment]
Thanq for ur concern towards ma doubt..
Intersection in the sense..

{a, b} -> {c} intersection {a} -> {c, d}
Every time {a, b,c,d} appear together in a transaction...
Hoping for ur reply.
