### ISSUE TITLE
GPL-3.0 license classifier?

### ISSUE THREAD

**Issue by tapdiego-amzn** [tommyod/Efficient-Apriori#51]
Hi — I noticed the license of this project is inconsistently identified as both [MIT](https://github.com/tommyod/Efficient-Apriori/blob/3cd50ae45af3fce3decbffee0df27c6bfaa6ffc1/setup.py#L43) and [GPLv3](https://github.com/tommyod/Efficient-Apriori/blob/3cd50ae45af3fce3decbffee0df27c6bfaa6ffc1/setup.py#L55) in your setup.py file. Since your [LICENSE](https://github.com/tommyod/Efficient-Apriori/blob/master/LICENSE) file clearly contains the MIT license text, I would assume that to be the actual license, but can you please clarify that?

**Comment by tommyod** [comment]
Yes, MIT is correct. Fixed it now. Thanks for pointing out the inconsistency!
