### ISSUE TITLE
Reducing H_1 update broken

### ISSUE THREAD

**Issue by selting** [tommyod/Efficient-Apriori#57]
Hello again,
thank you to @hprshayan for addressing #45 in #53.
However, the following example fails for me although all tests succeed:

```python
from efficient_apriori.apriori import apriori
transactions = [(1, 2, 3), (1, 2, 3), (1, 2, 3), (1, 2), (2, 3)]
apriori(transactions, 0.4, 0.8)
```

This is due to H_1 being empty at the time of entering _ap_genrules. Thus, the check [`if len(itemset) <= (len(H_m[0]) + 1)`](https://github.com/tommyod/Efficient-Apriori/blob/master/efficient_apriori/rules.py#L406) will give an IndexError.

If you could confirm that the example also fails for you, I might get around to creating a PR.

**Comment by tommyod** [comment]
I can confirm that it fails here too.

Would reverting https://github.com/tommyod/Efficient-Apriori/pull/53 fix this? 

We need a test for this case! A PR would be greatly appreciated!

**Comment by hprshayan** [comment]
Hi @selting,
Thank you for the note. I confirm the example also fails for me for the reason you mentioned. I have a solution for that. I can create a PR for that.

**Comment by tommyod** [comment]
Closed by https://github.com/tommyod/Efficient-Apriori/pull/58
