### ISSUE TITLE
weighted Association rule mining

### ISSUE THREAD

**Issue by guyq1997** [tommyod/Efficient-Apriori#60]
Hello Tommy,

 I am a newbie who just started writing code. I downloaded your code and made some small changes to implement weighted ARM for manufacturing data, I wonder if you are interested and can give me some suggestions to optimize the code?

Best regards
Yuqiang

**Comment by tommyod** [comment]
Hi,

Sorry, I don't have available time to help you optimize code if you're a Python beginner. I suggest buying a good book about Python or studying repositories on GitHub to learn.
