### ISSUE TITLE
Replace setup.py with pyproject.toml

### ISSUE THREAD

**Issue by tommyod** [tommyod/Efficient-Apriori#71]
Anyone wanna grab this task? Let me know!

**Comment by saad1998** [comment]
Hi @tommyod I would like to work on this issue.

**Comment by tommyod** [comment]
Great! Feel free to open a PR when you have something! Should be a relatively straightforward task, see e.g.
https://packaging.python.org/en/latest/guides/writing-pyproject-toml/

**Comment by saad1998** [comment]
Hi @tommyod I have created a PR. Please let me know if it needs anything else. Thanks
