### ISSUE TITLE
interpret the output

### ISSUE THREAD

**Issue by pinglewang** [tommyod/Efficient-Apriori#75]
Is there a way to visualize the output (i.e., itemsets and rules)? For example, the mlxtend Apriori can generate and return statistics such as lift, which allows one to visualize the strength of the association. Can we do something similar to the heatmap presented in the article below (the last set of figure): https://medium.com/analytics-vidhya/market-basket-analysis-association-rule-mining-with-visualizations-cda24d537019

**Comment by tommyod** [comment]
Rules have lift associated with them, see here:
https://github.com/tommyod/Efficient-Apriori/blob/b6d4b25dff22deb2b6c1a94e9b480234ecb8a3f1/efficient_apriori/rules.py#L98

You as the user can retrieve the values and visualize them. Visualization is outside of the scope of this library, and I do not have time to walk you through how to create a heatmap like that. But there is no reason why it should not be possible.
